/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cppModel_cppModel */

#ifndef _Included_cppModel_cppModel
#define _Included_cppModel_cppModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cppModel_cppModel
 * Method:    ModelMotion
 * Signature: ([D[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_cppModel_cppModel_ModelMotion
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     cppModel_cppModel
 * Method:    ModelReadConfig
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_cppModel_cppModel_ModelReadConfig
  (JNIEnv *, jclass, jcharArray);

/*
 * Class:     cppModel_cppModel
 * Method:    ModelScout
 * Signature: (DDDDDI)I
 */
JNIEXPORT jint JNICALL Java_cppModel_cppModel_ModelScout
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
